version = 1

# Project files.
[[annotations]]
path = [
  ".gitignore",
  ".vscode/extensions.json",
  "README.md",
  "package.json",
  "tsconfig.json",
  "tsconfig.node.json",
  "src-tauri/.gitignore",
  "src-tauri/capabilities/default.json",
  "src-tauri/tauri.conf.json",
]
SPDX-FileCopyrightText = "2026 Ethan Henderson"
SPDX-License-Identifier = "MIT OR Apache-2.0"

# Generated lockfiles.
[[annotations]]
path = ["package-lock.json", "src-tauri/Cargo.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Ethan Henderson"
SPDX-License-Identifier = "MIT OR Apache-2.0"
